name: todo_task
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.0.0
  connectivity_plus: ^2.3.5
  build_runner: ^2.4.10
  flutter_screenutil: ^5.7.0
  dropdown_button2: ^2.3.9
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  kiwi: ^5.0.0
  bloc: ^8.1.4
  shared_preferences: ^2.2.3

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
